[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false

[colors.normal]
black   = '#15161E'
red     = '#FC0D65'
magenta = '#FC0D65'
green   = '#9ECE6A'
yellow  = '#E0AF68'
blue    = '#356CE6'
cyan    = '#44D3FC'
white   = '#818AB3'

[colors.bright]
black   = '#2A334A'
red     = '#FD689F'
magenta = '#FD689F'
green   = '#C0E09F'
yellow  = '#ECCEA2'
blue    = '#44D3FC'
cyan    = '#81E2FD'
white   = '#C0CAF5'

[colors.cursor]
cursor  = '#C0CAF5'
text    = '#15161E'

[colors.primary]
background = '#15161E'
foreground = '#818AB3'

[colors.search.focused_match]
background = "#F4DBD6"
foreground = "#24273A"

[colors.search.matches]
background = "#A5ADCB"
foreground = "#24273A"

[colors.selection]
background = "#24293B"
text       = "#818AB3"

[colors.vi_mode_cursor]
cursor = "#818AB3"
text   = "#15161E"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
blinking = "On"
shape = "Block"

[font]
size = 16

[font.normal]
family = "SF Mono"
# family = "GoMono Nerd Font"
style = "Semibold"

[font.bold]
family = "SF Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove NF"
style = "Semibold Italic"

[font.bold_italic]
family = "SF Mono"
style = "Bold Italic"

[font.offset]
x = 0
y = -2

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 5

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
args = ["-l"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Windowed"

[window.padding]
x = 4
y = 5
