[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = false

[colors.normal]
black   = '#15161E'
red     = '#F22E52'
green   = '#9ECE6A'
yellow  = '#FABA4A'
blue    = '#7AA2F7'
magenta = '#FC0D65'
cyan    = '#44D3FC'
white   = '#818AB3'

[colors.bright]
black   = '#414868'
red     = '#F5617C'
green   = '#B6DC8F'
yellow  = '#E0AF68'
blue    = '#6694FA'
magenta = '#FC0D65'
cyan    = '#44D3FC'
white   = '#C0CAF5'

[colors.cursor]
cursor  = '#C0CAF5'
text    = '#15161E'

[colors.primary]
background = '#15161E'
foreground = '#818AB3'

[colors.search.focused_match]
background = "#F4DBD6"
foreground = "#24273A"

[colors.search.matches]
background = "#A5ADCB"
foreground = "#24273A"

[colors.selection]
background = "#24293B"
text       = "#818AB3"

[colors.vi_mode_cursor]
cursor = "#818AB3"
text   = "#15161E"

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"
blinking = "Always"

[font]
size = 14

[font.normal]
family = "SF Mono"
# family = "GoMono Nerd Font"
style = "Semibold"

[font.bold]
family = "SF Mono"
style = "Bold"

[font.italic]
family = "CaskaydiaCove NF"
style = "Semibold Italic"

[font.bold_italic]
family = "CaskaydiaCove NF"
style = "Bold Italic"

[font.offset]
x = 0
y = -2

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 5

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
args = ["-l"]
program = "/bin/zsh"

[cursor.vi_mode_style]
shape = "Block"
blinking = "Always"

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Windowed"

[window.padding]
x = 2
y = 2

[[keyboard.bindings]]
key = "Return"
mods = "Alt"
action = "ToggleFullscreen"
